/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppCampaignsNewRouteImport } from './routes/_app/campaigns/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCampaignsCheckoutRouteImport } from './routes/api/campaigns/checkout'
import { Route as ApiCampaignsCreateRouteImport } from './routes/api/campaigns/create'
import { Route as ApiStripeDashboardRouteImport } from './routes/api/stripe/dashboard'
import { Route as ApiStripeOnboardRouteImport } from './routes/api/stripe/onboard'
import { Route as ApiStripePaymentsWebhookRouteImport } from './routes/api/stripe/payments-webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsCheckoutRoute = ApiCampaignsCheckoutRouteImport.update({
  id: '/api/campaigns/checkout',
  path: '/api/campaigns/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsCreateRoute = ApiCampaignsCreateRouteImport.update({
  id: '/api/campaigns/create',
  path: '/api/campaigns/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeDashboardRoute = ApiStripeDashboardRouteImport.update({
  id: '/api/stripe/dashboard',
  path: '/api/stripe/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeOnboardRoute = ApiStripeOnboardRouteImport.update({
  id: '/api/stripe/onboard',
  path: '/api/stripe/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePaymentsWebhookRoute =
  ApiStripePaymentsWebhookRouteImport.update({
    id: '/api/stripe/payments-webhook',
    path: '/api/stripe/payments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/connections': typeof AppConnectionsRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/campaigns/checkout': typeof ApiCampaignsCheckoutRoute
  '/api/campaigns/create': typeof ApiCampaignsCreateRoute
  '/api/stripe/dashboard': typeof ApiStripeDashboardRoute
  '/api/stripe/onboard': typeof ApiStripeOnboardRoute
  '/api/stripe/payments-webhook': typeof ApiStripePaymentsWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/connections': typeof AppConnectionsRoute
  '/': typeof AppIndexRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/campaigns/checkout': typeof ApiCampaignsCheckoutRoute
  '/api/campaigns/create': typeof ApiCampaignsCreateRoute
  '/api/stripe/dashboard': typeof ApiStripeDashboardRoute
  '/api/stripe/onboard': typeof ApiStripeOnboardRoute
  '/api/stripe/payments-webhook': typeof ApiStripePaymentsWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/campaigns/checkout': typeof ApiCampaignsCheckoutRoute
  '/api/campaigns/create': typeof ApiCampaignsCreateRoute
  '/api/stripe/dashboard': typeof ApiStripeDashboardRoute
  '/api/stripe/onboard': typeof ApiStripeOnboardRoute
  '/api/stripe/payments-webhook': typeof ApiStripePaymentsWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/connections'
    | '/campaigns/new'
    | '/api/auth/$'
    | '/api/campaigns/checkout'
    | '/api/campaigns/create'
    | '/api/stripe/dashboard'
    | '/api/stripe/onboard'
    | '/api/stripe/payments-webhook'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/connections'
    | '/'
    | '/campaigns/new'
    | '/api/auth/$'
    | '/api/campaigns/checkout'
    | '/api/campaigns/create'
    | '/api/stripe/dashboard'
    | '/api/stripe/onboard'
    | '/api/stripe/payments-webhook'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/_app'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/_app/connections'
    | '/_app/'
    | '/_app/campaigns/new'
    | '/api/auth/$'
    | '/api/campaigns/checkout'
    | '/api/campaigns/create'
    | '/api/stripe/dashboard'
    | '/api/stripe/onboard'
    | '/api/stripe/payments-webhook'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCampaignsCheckoutRoute: typeof ApiCampaignsCheckoutRoute
  ApiCampaignsCreateRoute: typeof ApiCampaignsCreateRoute
  ApiStripeDashboardRoute: typeof ApiStripeDashboardRoute
  ApiStripeOnboardRoute: typeof ApiStripeOnboardRoute
  ApiStripePaymentsWebhookRoute: typeof ApiStripePaymentsWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/checkout': {
      id: '/api/campaigns/checkout'
      path: '/api/campaigns/checkout'
      fullPath: '/api/campaigns/checkout'
      preLoaderRoute: typeof ApiCampaignsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/create': {
      id: '/api/campaigns/create'
      path: '/api/campaigns/create'
      fullPath: '/api/campaigns/create'
      preLoaderRoute: typeof ApiCampaignsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/dashboard': {
      id: '/api/stripe/dashboard'
      path: '/api/stripe/dashboard'
      fullPath: '/api/stripe/dashboard'
      preLoaderRoute: typeof ApiStripeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/onboard': {
      id: '/api/stripe/onboard'
      path: '/api/stripe/onboard'
      fullPath: '/api/stripe/onboard'
      preLoaderRoute: typeof ApiStripeOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/payments-webhook': {
      id: '/api/stripe/payments-webhook'
      path: '/api/stripe/payments-webhook'
      fullPath: '/api/stripe/payments-webhook'
      preLoaderRoute: typeof ApiStripePaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCampaignsCheckoutRoute: ApiCampaignsCheckoutRoute,
  ApiCampaignsCreateRoute: ApiCampaignsCreateRoute,
  ApiStripeDashboardRoute: ApiStripeDashboardRoute,
  ApiStripeOnboardRoute: ApiStripeOnboardRoute,
  ApiStripePaymentsWebhookRoute: ApiStripePaymentsWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
